name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: spheruby:latest

    steps:
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.IMAGE_TAG }}

      - name: Lint
        run: docker run ${{ env.IMAGE_TAG }} rake lint
        
      - name: Spec
        run: docker run ${{ env.IMAGE_TAG }} rake spec
